namespace Albion.Network;

// Explicit factories keep packet constructors available in trimmed Android builds.
internal static class PacketFactory
{
    private static readonly IReadOnlyDictionary<Type, Func<Dictionary<byte, object>, object>> Factories =
        new Dictionary<Type, Func<Dictionary<byte, object>, object>>
        {
            [typeof(AlbionDataAvalonia.Network.Events.BankVaultInfoEvent)] = p => new AlbionDataAvalonia.Network.Events.BankVaultInfoEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.GuildVaultInfoEvent)] = p => new AlbionDataAvalonia.Network.Events.GuildVaultInfoEvent(p),
            [typeof(AlbionDataAvalonia.Network.Requests.JoinRequest)] = p => new AlbionDataAvalonia.Network.Requests.JoinRequest(p),
            [typeof(AlbionDataAvalonia.Network.Events.AttachItemContainerEvent)] = p => new AlbionDataAvalonia.Network.Events.AttachItemContainerEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.DebugEventProbeEvent)] = p => new AlbionDataAvalonia.Network.Events.DebugEventProbeEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.DetachItemContainerEvent)] = p => new AlbionDataAvalonia.Network.Events.DetachItemContainerEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.EstimatedMarketValueUpdateEvent)] = p => new AlbionDataAvalonia.Network.Events.EstimatedMarketValueUpdateEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.FarmableObjectInfoEvent)] = p => new AlbionDataAvalonia.Network.Events.FarmableObjectInfoEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.FarmBuildingInfoEvent)] = p => new AlbionDataAvalonia.Network.Events.FarmBuildingInfoEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.FestivitiesUpdateEvent)] = p => new AlbionDataAvalonia.Network.Events.FestivitiesUpdateEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.FullAchievementInfoEvent)] = p => new AlbionDataAvalonia.Network.Events.FullAchievementInfoEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.HarvestFinishedEvent)] = p => new AlbionDataAvalonia.Network.Events.HarvestFinishedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.HealthUpdateEvent)] = p => new AlbionDataAvalonia.Network.Events.HealthUpdateEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.HealthUpdatesEvent)] = p => new AlbionDataAvalonia.Network.Events.HealthUpdatesEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.InCombatStateUpdateEvent)] = p => new AlbionDataAvalonia.Network.Events.InCombatStateUpdateEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.InventoryDeleteItemEvent)] = p => new AlbionDataAvalonia.Network.Events.InventoryDeleteItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.InventoryPutItemEvent)] = p => new AlbionDataAvalonia.Network.Events.InventoryPutItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.LeaveEvent)] = p => new AlbionDataAvalonia.Network.Events.LeaveEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.LootChestOpenedEvent)] = p => new AlbionDataAvalonia.Network.Events.LootChestOpenedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewBuildingEvent)] = p => new AlbionDataAvalonia.Network.Events.NewBuildingEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewCharacterEvent)] = p => new AlbionDataAvalonia.Network.Events.NewCharacterEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewEquipmentItemEvent)] = p => new AlbionDataAvalonia.Network.Events.NewEquipmentItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewEquipmentItemLegendarySoulEvent)] = p => new AlbionDataAvalonia.Network.Events.NewEquipmentItemLegendarySoulEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewFurnitureItemEvent)] = p => new AlbionDataAvalonia.Network.Events.NewFurnitureItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewJournalItemEvent)] = p => new AlbionDataAvalonia.Network.Events.NewJournalItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewKillTrophyItemEvent)] = p => new AlbionDataAvalonia.Network.Events.NewKillTrophyItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewLaborerItemEvent)] = p => new AlbionDataAvalonia.Network.Events.NewLaborerItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewLootChestEvent)] = p => new AlbionDataAvalonia.Network.Events.NewLootChestEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewLootEvent)] = p => new AlbionDataAvalonia.Network.Events.NewLootEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewMobEvent)] = p => new AlbionDataAvalonia.Network.Events.NewMobEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewSiegeBannerItemEvent)] = p => new AlbionDataAvalonia.Network.Events.NewSiegeBannerItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.NewSimpleItemEvent)] = p => new AlbionDataAvalonia.Network.Events.NewSimpleItemEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.OtherGrabbedLootEvent)] = p => new AlbionDataAvalonia.Network.Events.OtherGrabbedLootEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartyDisbandedEvent)] = p => new AlbionDataAvalonia.Network.Events.PartyDisbandedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartyJoinedEvent)] = p => new AlbionDataAvalonia.Network.Events.PartyJoinedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartyLootItemsEvent)] = p => new AlbionDataAvalonia.Network.Events.PartyLootItemsEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartyLootItemsRemovedEvent)] = p => new AlbionDataAvalonia.Network.Events.PartyLootItemsRemovedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartyLootItemTypesRemovedEvent)] = p => new AlbionDataAvalonia.Network.Events.PartyLootItemTypesRemovedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartyOnClusterPartyJoinedEvent)] = p => new AlbionDataAvalonia.Network.Events.PartyOnClusterPartyJoinedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartyPlayerJoinedEvent)] = p => new AlbionDataAvalonia.Network.Events.PartyPlayerJoinedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartyPlayerLeftEvent)] = p => new AlbionDataAvalonia.Network.Events.PartyPlayerLeftEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PartySetRoleFlagEvent)] = p => new AlbionDataAvalonia.Network.Events.PartySetRoleFlagEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PlayerCountsEvent)] = p => new AlbionDataAvalonia.Network.Events.PlayerCountsEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.PremiumChangedEvent)] = p => new AlbionDataAvalonia.Network.Events.PremiumChangedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.RedZoneWorldMapEvent)] = p => new AlbionDataAvalonia.Network.Events.RedZoneWorldMapEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.RewardGrantedEvent)] = p => new AlbionDataAvalonia.Network.Events.RewardGrantedEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.TakeSilverEvent)] = p => new AlbionDataAvalonia.Network.Events.TakeSilverEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.TimeSyncEvent)] = p => new AlbionDataAvalonia.Network.Events.TimeSyncEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.UpdateFameEvent)] = p => new AlbionDataAvalonia.Network.Events.UpdateFameEvent(p),
            [typeof(AlbionDataAvalonia.Network.Events.UpdateLootChestEvent)] = p => new AlbionDataAvalonia.Network.Events.UpdateLootChestEvent(p),
            [typeof(AlbionDataAvalonia.Network.Requests.AuctionBuyOfferRequest)] = p => new AlbionDataAvalonia.Network.Requests.AuctionBuyOfferRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.AuctionGetItemAverageStatsRequest)] = p => new AlbionDataAvalonia.Network.Requests.AuctionGetItemAverageStatsRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.AuctionSellSpecificItemRequestRequest)] = p => new AlbionDataAvalonia.Network.Requests.AuctionSellSpecificItemRequestRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.BuildingRenovationRequest)] = p => new AlbionDataAvalonia.Network.Requests.BuildingRenovationRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.DebugRequestProbeRequest)] = p => new AlbionDataAvalonia.Network.Requests.DebugRequestProbeRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.FarmingActionRequest)] = p => new AlbionDataAvalonia.Network.Requests.FarmingActionRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.FishingCancelRequest)] = p => new AlbionDataAvalonia.Network.Requests.FishingCancelRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.FishingFinishRequest)] = p => new AlbionDataAvalonia.Network.Requests.FishingFinishRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.FishingStartRequest)] = p => new AlbionDataAvalonia.Network.Requests.FishingStartRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.InventoryMoveGivenItemsRequest)] = p => new AlbionDataAvalonia.Network.Requests.InventoryMoveGivenItemsRequest(p),
            [typeof(AlbionDataAvalonia.Network.Requests.InventoryMoveItemRequest)] = p => new AlbionDataAvalonia.Network.Requests.InventoryMoveItemRequest(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AssetOverviewResponse)] = p => new AlbionDataAvalonia.Network.Responses.AssetOverviewResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AssetOverviewTabContentResponse)] = p => new AlbionDataAvalonia.Network.Responses.AssetOverviewTabContentResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AssetOverviewTabsResponse)] = p => new AlbionDataAvalonia.Network.Responses.AssetOverviewTabsResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AssetOverviewUnfreezeCacheResponse)] = p => new AlbionDataAvalonia.Network.Responses.AssetOverviewUnfreezeCacheResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AuctionBuyOfferResponse)] = p => new AlbionDataAvalonia.Network.Responses.AuctionBuyOfferResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AuctionGetGoldAverageStatsResponse)] = p => new AlbionDataAvalonia.Network.Responses.AuctionGetGoldAverageStatsResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AuctionGetItemAverageStatsResponse)] = p => new AlbionDataAvalonia.Network.Responses.AuctionGetItemAverageStatsResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AuctionGetLoadoutOffersResponse)] = p => new AlbionDataAvalonia.Network.Responses.AuctionGetLoadoutOffersResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AuctionGetOffersResponse)] = p => new AlbionDataAvalonia.Network.Responses.AuctionGetOffersResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AuctionGetRequestsResponse)] = p => new AlbionDataAvalonia.Network.Responses.AuctionGetRequestsResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.AuctionSellSpecificItemRequestResponse)] = p => new AlbionDataAvalonia.Network.Responses.AuctionSellSpecificItemRequestResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.ChangeClusterResponse)] = p => new AlbionDataAvalonia.Network.Responses.ChangeClusterResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.DebugResponseProbeResponse)] = p => new AlbionDataAvalonia.Network.Responses.DebugResponseProbeResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.FarmingActionResponse)] = p => new AlbionDataAvalonia.Network.Responses.FarmingActionResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.FishingFinishResponse)] = p => new AlbionDataAvalonia.Network.Responses.FishingFinishResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.GetIslandInfosResponse)] = p => new AlbionDataAvalonia.Network.Responses.GetIslandInfosResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.GetMailInfosResponse)] = p => new AlbionDataAvalonia.Network.Responses.GetMailInfosResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.JoinResponse)] = p => new AlbionDataAvalonia.Network.Responses.JoinResponse(p),
            [typeof(AlbionDataAvalonia.Network.Responses.ReadMailResponse)] = p => new AlbionDataAvalonia.Network.Responses.ReadMailResponse(p),
        };

    public static T Create<T>(Dictionary<byte, object> parameters) where T : class =>
        Factories.TryGetValue(typeof(T), out var factory)
            ? (T)factory(parameters)
            : throw new NotSupportedException($"No packet factory registered for {typeof(T).Name}.");
}
